### PR TITLE
Stu3 template fixes

### PR DESCRIPTION
**Pull request by lmckenzi**

### CODE REVIEW

**Review by grahamegrieve — COMMENTED** [review]
uh, why? I don't like these changes at all

**Comment by lmckenzi** [comment]
The relevant value sets don't exist for all versions of FHIR, so defining them inline was the best way to make this work.  Why do you not like the change?

**Comment by grahamegrieve** [comment]
I generally try to avoid defining them in code. Why aren't they in THO? Or should they be in pubpack?

**Comment by lmckenzi** [comment]
Is THO used with STU3 and earlier releases?
In any event, it only has value sets for 2-char and 3-char country, not numeric.  Also doesn't have the state codes.

**Comment by grahamegrieve** [comment]
THO is loaded for R3 but not R2, I think. You can move them out of the code at some stage

**Pull request merged**
