### PR TITLE
Add Gherkin, json, xml, and text to AdjunctFileLoader.java

### LINKED ISSUE #355: ig-loader QA report errors
The ig-loader functionality of the IG Builder, aka [Binary Adjunct Files](https://confluence.hl7.org/pages/viewpage.action?pageId=66938614#ImplementationGuideParameters-BinaryAdjunctFiles) throws QA report errors. The errors are caused because the IG Builder does not do everything it says it will do. 

The functionality does work, it does pull the file into base64encoded element.

QA report errors:
- att-1: 'If the Attachment has data, it SHALL have a contentType' Rule 'If the Attachment has data, it SHALL have a contentType' Failed
- Unknown file type foobar.txt

So:
- [ ] does not populate the contentType element, although the confluence explanation says it will.

It would be nice if the ig-loader filename trick worked while also allowing the other elements to be filled out. But the ig-loader feature requires that the attachment is empty except for the attachment.id holding the prepended filename.

See [sushi chat](https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/ig-loader.20examples)

### LINKED ISSUE #930: acceptable file extension for Binary of ".feature"
Gherkin script files use the file extension `.feature`. The IG publisher will not load these files into Binary, 

Given sushi-config.yaml
```
resources:
  Binary/give-consent.feature:
    extension:
      - url: http://hl7.org/fhir/StructureDefinition/implementationguide-resource-format
        valueCode: "text/x-gherkin"
```

gives this error in the IG publisher
```
Stack Dump (for debugging):                                                                          (00:00.001 / 00:43.015, 505Mb)
java.lang.Exception: Unable to find the source file for Binary/give-consent.feature: not specified, so tried Binary-give-consent.feature.xml, give-consent.feature.Binary.xml, Binary-give-consent.feature.json, Binary/give-consent.feature.xml, Binary/give-consent.feature.json, give-consent.feature.xml, and give-consent.feature.json (and lowercase resource name variants) in dirs [C:\Users\johnm\git\ConsentWithSeg-testing\fsh-generated\resources, C:\Users\johnm\git\ConsentWithSeg-testing\fsh-generated\resources, C:\Users\johnm\git\ConsentWithSeg-testing\input\tests]
        at org.hl7.fhir.igtools.publisher.SimpleFetcher.fetch(SimpleFetcher.java:246)
        at org.hl7.fhir.igtools.publisher.Publisher.load(Publisher.java:4423)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1172)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:1016)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:13007)

```

----------------------

Loading them using ig-loader

```
Instance: B-gerkin-script
InstanceOf: Binary
Title: "Binary Gerkin script"
Description: "Example of a binary Gerkin script using Binary."
* contentType = #text/x-gherkin
* data = "ig-loader-give-consent.feature"
```

but this results in a QA ERROR
> Unknown file type give-consent.feature

It seems that the IG publisher needs to be told that `.feature` is an okay extension.

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #930
close #355

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
@grahamegrieve

**Comment by JohnMoehrke** [comment]
Note that #355 would like similar support for json, xml, and text. Should I add them to this, or do we need to discuss them?

**Comment by JohnMoehrke** [comment]
committee review agreed to add json, xml, and text

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
