### PR TITLE
Add checkstyle plugin to pom.xml

### PR DESCRIPTION
**Pull request by jkiddo**
run 'mvn site' to see the calculated results in the 'target/site/' folder

### CODE REVIEW

**Comment by grahamegrieve** [comment]
@dotasek is this something that's good for us?

**Comment by dotasek** [comment]
Yes, having checkstyle enabled would be great, but let's not merge this in yet. 

I just set up checkstyle in core, and it's run as part of the build. It would be good to have it set up with the same rules here. 

See: https://github.com/hapifhir/org.hl7.fhir.core/pull/1122

**Comment by dotasek** [comment]
@jkiddo I added checkstyle to the build in this PR https://github.com/HL7/fhir-ig-publisher/pull/624 and will set you as a reviewer. I think that approach is slightly more rigorous and can be expanded later to catch more issues.

I'll leave this open until that PR is approved and merged.

**Comment by dotasek** [comment]
https://github.com/HL7/fhir-ig-publisher/pull/624 has been approved and merged. Closing this PR.

**Pull request closed without merging**
