### PR TITLE
Toc fixes

### PR DESCRIPTION
**Pull request by lmckenzi**
NOTE: Requires Grahame to push a change to the pubpack.

### CODE REVIEW

**Review by grahamegrieve — COMMENTED** [review]
why the changes to publisher.java?

**Comment by lmckenzi** [comment]
The only thing changed is publisher.java - that's where the ToC is defined.

Presume you mean `else if (defaultBusinessVersion != null && bc.getVersion()==null)`?
That's because the prior code was failing when bc.getVersion() was null and throwing an NPI.

**Comment by grahamegrieve** [comment]
The correct fix is else if (defaultBusinessVersion != null && !bc.getVersionElement().isEmpty())

**Comment by lmckenzi** [comment]
Fixed

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
