### PR TITLE
Fix issue with generated IG in output folder not including all parame…

### PR DESCRIPTION
**Pull request by lmckenzi**
…ters

### CODE REVIEW

**Comment by grahamegrieve** [comment]
Please explain this change. I don't understand why it's a good idea

**Comment by lmckenzi** [comment]
Eric had raised an issue that all of the parameters weren't showing up in the published IG.  Different templates inject different parameters.  Presumably knowing what actually drove publication is deemed to be relevant.

**Comment by grahamegrieve** [comment]
My question wasn't about the intent of the change, but why the actual code changes proposed in the PR are a good idea. Why is it safe not to load the element model?

**Comment by lmckenzi** [comment]
Because what it loads is the original IG, not the one with the modifications from the template.

**Pull request merged**
