### PR TITLE
Add logic to link TestScripts and Profiles

### PR DESCRIPTION
**Pull request by rettema**
### What does this Pull Request do?
Add logic that links TestScript resources to Profiles (StructureDefinitions).

### Why?
The FHIR community has been increasingly interested in provided better support for testing artifacts within IGs. This additional logic is an initial enhancement that allows IGs generated from the HL7 IG template to incorporate and list TestScript resources with their associated FHIR Profiles (StructureDefinitions).

### How?
Minor code additions to two (2) classes that provide the needed links between TestScripts and StructureDefinitions:
* **FetchedResource** 
  * New List\<String\> variable **testProfiles** to hold the canonical url(s) of the FHIR Profile(s) referenced in a TestScript resource; along with corresponding getter and setter methods
  * New HashSet\<FetchedResource\> variable **foundTestScripts** to hold the linked TestScript resource(s) to a StructureDefinition resource; along with corresponding getter and setter methods
* **Publisher**
  * New Set\<FetchedResource\> variable **testscripts** to hold the list of all TestScript resources for the IG
  * **load()** method - new logic in iteration over the IG resources to populate the **testscripts** list; and populate each TestScript's **testProfiles** list
  * **generateSummaryOutputs()** method - new logic to iterate over all **testscripts** and for each linked Profile, update the corresponding StructureDefinition FetchedResource list of **foundTestScripts**
  * **addPageDataRow()** method - add new *testscripts* argument, passed in from profile processing; adds list of linked TestScripts to the Profile page

### CODE REVIEW

**Comment by costateixeira** [comment]
I can't understand the code, but I think that the link from TestScripts should be to any resource. In fact, I think StructureDefinitions would not be among the most common artifacts. The most common ones, I guess, would be 
* CapabilityStatements
* Requirements
* OperationDefinitions
* (other Definitions?)
Can we rename / adjust accordingly? e.g. renaming testProfiles to testArtifacts. and ensuring that this works for any artifact, not Profiles

**Comment by rettema** [comment]
@costateixeira, the TestScript.profile element is the specific link to StructureDefinition that is the basis for this initial enhancement. That being said, yes, the introduction of the TestScript.scope.artifact element in R5 does provide the opportunity to link TestScripts to the other canonical resources. I would prefer addressing this request as a separate enhancement as this will take additional research in conjunction with the HL7 templates for potential display in the IG content.

**Comment by rettema** [comment]
@costateixeira, saw your 2nd comment after sending my reply. Yes, renaming the variable now in anticipation of future use outside of StructureDefinition make sense.

**Comment by costateixeira** [comment]
Actually, I thought we were talking about TestScript.scope - that is the
link to the resource that is being tested, right?

**Comment by rettema** [comment]
TestScript.scope is new for R5 and will represent the full list of linked resources being tested. TestScript.profile has and will remain the specific link to the FHIR Profile (StructureDefinition) used for the validation assert - assert.validateProfileId.

**Comment by costateixeira** [comment]
We had considered preadopting the R5 element as an extension for that. I
think we should have only one entry point - one way of defining how the
TestScript points at what it is supposed to test. If we have more than one,
we need to revisit the resource - I can make a ballot comment for that.

If .profile is indeed be superseded(?)/overlapping with scope, I don't
think we should do this on .profile but instead just do it on the extension
as if it were the .scope element - otherwise I think this will be very
difficult to handle in R5 IGs (which would have to use the wrong element)
or we need to change the code again.
Is it doable in the code to consider the element  .scope preadopted as an
extension?

see https://github.com/HL7/fhir-ig-publisher/issues/108

**Comment by rettema** [comment]
Yes, the logic to parse the TestScript resource for links to conformance resources uses the FHIR org.hl7.fhir.r5.elementmodel.Element representation which allows for a generic (and forgiving) mechanism of traversing the resource structure. So, the code can be written to allow for known variations of where the canonical values are found. This means we can continue to use TestScript.profile along with the new R5 TestScript.scope as well as any potential new extension representing 'scope'.

**Comment by costateixeira** [comment]
So implementers would be able to use either .profile OR .scope in R5? That
is ok for the tooling - but I think the TestScript resource should be
clarified (other discussion).

And for R4, can we use the extension? Happy to contribute to the PR if I
someone can guide me.
I don't think we would ever use the .profile (because it is limiting and
doesn't seem to mean what we need, which is "the conformance artifact that
is covered by this test case".
Thanks

**Comment by rettema** [comment]
> I don't think we would ever use the .profile (because it is limiting and doesn't seem to mean what we need
As I stated above, TestScript.profile is and has been for a very specific use; i.e. assert.validateProfileId. So, it is functionally needed by the Test Engine. I'm not sure we could simply just switch over to TestScript.scope.

In the meantime, let me continue to work on this where we make the TestScript links more generic; i.e. "testProfiles" --> "testArtifacts". I'll keep you updated. Thanks!

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
