### PR TITLE
Update CQL Translator Format Options 

### PR DESCRIPTION
**Pull request by c-schuler**
- Fixed CQL translator options format checks

Resolution for #822

### CODE REVIEW

**Review by JPercival — APPROVED** [review]

**Comment by bkaney** [comment]
Hi -- This is a pretty big blocker as the current IG Publisher doesn't work with CQL-related projects. @brynrhodes  @JPercival  - can we get this merged?

**Review by grahamegrieve — APPROVED** [review]
ok

**Comment by grahamegrieve** [comment]
so I merged this, and now I get:

Translating CQL source                                                                               (00:00.088 / 00:13.053, 423Mb)
Translating CQL source in folder /Users/grahamegrieve/work/test-igs/example.fhir.uv.myig/input/cql   (00:00.000 / 00:13.053, 423Mb)
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.cqframework.cql.cql2elm.CqlTranslatorOptions$Format` from String "JXSON": not one of the values accepted for Enum class: [JSON, COFFEE, XML]
 at [Source: (FileReader); line: 11, column: 6] (through reference chain: org.cqframework.cql.cql2elm.CqlTranslatorOptions["formats"]->java.util.HashSet[1])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1996)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1224)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:356)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._fromString(EnumDeserializer.java:230)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:198)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeWithUnwrapped(BeanDeserializer.java:727)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:347)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3690)
	at org.cqframework.cql.cql2elm.CqlTranslatorOptionsMapper.fromReader(CqlTranslatorOptionsMapper.java:23)
	at org.cqframework.cql.cql2elm.CqlTranslatorOptionsMapper.fromFile(CqlTranslatorOptionsMapper.java:14)
	at org.hl7.fhir.igtools.publisher.CqlSubSystem.getTranslatorOptions(CqlSubSystem.java:324)
	at org.hl7.fhir.igtools.publisher.CqlSubSystem.translateFolder(CqlSubSystem.java:363)
	at org.hl7.fhir.igtools.publisher.CqlSubSystem.execute(CqlSubSystem.java:263)
	at org.hl7.fhir.igtools.publisher.Publisher.load(Publisher.java:4525)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1123)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:974)

**Comment by brynrhodes** [comment]
This is due to the sample-ig, needs these updates here: https://github.com/FHIR/sample-ig/pull/61

**Pull request merged**
