### PR TITLE
Don't treat inter-version extensions as errors

### PR DESCRIPTION
**Pull request by lmckenzi**

### CODE REVIEW

**Comment by grahamegrieve** [comment]
This regex looks very permissive compared to the scope of the problem?

**Comment by lmckenzi** [comment]
It's already in the scope of "starts with "http://hl7.org/fhir/StructureDefinition", so we're really just checking the format of the id.

**Comment by grahamegrieve** [comment]
It allows lots of non-valid extensions. In fact, it won't complain about any HL7-ish extension, whether they're valid or not? that's not good

**Comment by lmckenzi** [comment]
Thoughts on a better process?

**Comment by grahamegrieve** [comment]
abandoned as I implemented an actual correct solution to this requirement

**Pull request closed without merging**
