### PR TITLE
Changes needed to support revised artifact table rendering

### PR DESCRIPTION
**Pull request by lmckenzi**

### CODE REVIEW

**Comment by grahamegrieve** [comment]
what does propagateStatus() do, and where is it documented?

**Comment by lmckenzi** [comment]
It migrates standards status and FMM through dependencies unless overridden.  Where do you want it to be documented?

**Comment by grahamegrieve** [comment]
Well, the parameters should be documented here: https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters. I suspect that the way standards status migrates should also be documented on that page, and also in the code

**Comment by lmckenzi** [comment]
Replaced by #386

**Pull request closed without merging**
