### PR TITLE
Test XSL Transformation

### PR DESCRIPTION
**Pull request by dotasek**
This PR refactors XSL Transformation into a testable class and verifies that the XSL transformation module included in the JRE is one that doesn't produce extra namespace prefixes.

### CODE REVIEW

**Review by grahamegrieve — APPROVED** [review]
ok. I mean, this is a good as a test, but it seems to me that it doesn't quite hit the spot, since whether it falis or not isn't due to our code, but due to the platform provider? Would it be good to run this test at the start of the IG publisher run?

**Comment by dotasek** [comment]
The change in core SHOULD ensure that there is no platform dependency. It explicitly uses Saxon, as it did before, when we got Saxon as a side-effect from HAPI. That will override the platform.

Maybe end users could go through the effort of configuring another TransformerFactory implementation when running IG publisher to override this, but I think it's an unlikely thing, and that in that case the test would interfere with their intent.

**Comment by grahamegrieve** [comment]
Well, all those things are true but what does this test actually test then? Does it fail if Saxon isn’t included?Sent from my iPhoneOn 7 Jan 2023, at 10:32 am, dotasek ***@***.***> wrote:﻿
The change in core SHOULD ensure that there is no platform dependency. It explicitly uses Saxon, as it did before, when we got Saxon as a side-effect from HAPI. That will override the platform.
Maybe end users could go through the effort of configuring another TransformerFactory implementation when running IG publisher to override this, but I think it's an unlikely thing, and that in that case the test would interfere with their intent.

**Comment by dotasek** [comment]
@grahamegrieve If saxon isn't included, this test MIGHT fail. It definitely fails on my machine. I imagine, as your computer didn't exhibit the same behaviour running the ig-publisher on the unicom IG, that there are some JRE distributions that could still pass.

**Comment by grahamegrieve** [comment]
ok

**Pull request merged**
