### PR TITLE
Feature configure Jekyll timeout

### PR DESCRIPTION
**Pull request by rob-reynolds**
ISSUE: https://github.com/HL7/fhir-ig-publisher/issues/429.

There are production content IGs that require Jekyll processing that exceeds the 5 minute default. Allow the value to be configured.

### CODE REVIEW

**Comment by rob-reynolds** [comment]
This may be too naïve an implementation to merge.

Not sure what the process is for adding things to the ImplementationGuideDefinitionParameterComponent type, whether that should be done first or if it should be 'trialed' like this until it warrants being added, etc.

Also, there are considerations for other ways configuration values can be read.

**Comment by rob-reynolds** [comment]
Note: there are also 2 branches with separate PRs merged into this:
- https://github.com/HL7/fhir-ig-publisher/pull/424
- https://github.com/HL7/fhir-ig-publisher/pull/425

**Review by grahamegrieve — COMMENTED** [review]
why rename JEKYLL_TIMEOUT to TOOL_TIMEOUT - it hasn't changed in function, it just gets less clear

**Comment by rob-reynolds** [comment]
There's an abstraction in place to allow the specific "tool" to change: https://github.com/HL7/fhir-ig-publisher/blob/e15e191c5a114f0b8cd9d2cd4ad287323daf0273/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java#L6573.

The intent was to implement at that level.  

I see the point re JEKYLL_TIMEOUT.  Are you OK with the rest being at the higher level?

**Comment by grahamegrieve** [comment]
It's a todo for me to get around to removing that abstraction - we've decided that we won't support anything other than Jekyll. And if I just possibly maybe did, there's no reason to think a different tool would even have a timeout, let alone the same one

**Comment by rob-reynolds** [comment]
Does that look better?  

I also added configuration in the json version.  I can remove that if it's not appropriate.

**Comment by rob-reynolds** [comment]
Deprecated

**Pull request closed without merging**
